apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: adwera/ts-fileupload-auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
            - name: NATS_CLUSTER_ID
              value: 'ts-fileupload'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: REDIS_HOST
              value: 'auth-redis-service'
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key
                  key: COOKIE_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET  

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000


