apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: adwera/ts-fileupload-data
          env:
            - name: MONGO_URI
              value: 'mongodb://data-mongo-service:27017/data'
            - name: NATS_CLUSTER_ID
              value: 'ts-fileupload'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'

---

apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data
  ports:
    - name: data
      protocol: TCP
      port: 5002
      targetPort: 5002


