apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-fileupload-database-pvc
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
